{{- $clientCACert := (lookup "v1" "Secret" .Values.messageQueue.amqStreams.namespace (printf "%s-clients-ca-cert" .Values.messageQueue.amqStreams.name)) -}}
{{- $clientCAKey := (lookup "v1" "Secret" .Values.messageQueue.amqStreams.namespace (printf "%s-clients-ca" .Values.messageQueue.amqStreams.name)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: maestro-mq-certs
  namespace: '{{ .Values.addOnManager.namespace }}'
type: kubernetes.io/tls
data:
{{- range $key, $value := $clientCACert.data }}
  {{- if eq $key "ca.crt" }}
  tls.crt: {{ $value }}
  {{- end }}
{{- end }}
{{- range $key, $value := $clientCAKey.data }}
  {{- if eq $key "ca.key" }}
  tls.key: {{ $value }}
  {{- end }}
{{- end }}
