apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-manager
  namespace: '{{ .Values.addOnManager.namespace }}'
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
