# RoleBinding for work mandatory permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:maestro-addon:manager
  namespace: '{{ .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:maestro-addon:manager
subjects:
  - kind: ServiceAccount
    name: maestro-addon-manager
