{{- $kafkaRoute := (lookup "route.openshift.io/v1" "Route" .Values.messageQueue.amqStreams.namespace (printf "%s-kafka-tls-bootstrap" .Values.messageQueue.amqStreams.name)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: maestro-kafka-config
  namespace: '{{ .Values.global.namespace }}'
stringData:
  config.yaml: |-
    bootstrapServer: {{- indent 1 (printf "%s:443" $kafkaRoute.spec.host) }}
    caFile: /secrets/certs/kafka/ca.crt
    clientCertFile: /secrets/certs/kafka/client.crt
    clientKeyFile: /secrets/certs/kafka/client.key
